language: c
script: asdf plugin-test envchain https://github.com/endorama/asdf-envchain.git 'envchain'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  # - osx
